server:
  port: 8080

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 123456789
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 956374525400-bglv4m9gq0pdh4d570bm45p70hq79t4v.apps.googleusercontent.com
            client-secret: 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

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
